### ISSUE TITLE
Can't get flatpickr to work in production/staging environment.

### ISSUE THREAD

**Issue by salex** [adrienpoly/rails_stimulus_flatpickr#15]
Probably not your fault, but you seem to understand this stuff better that I do and maybe you can point me in the right direction. I don't do a lot of java/coffee script, enough to get by. I tried to modernize an app and more or less started from scratch with rails 6, web packer, no jQuery. Also had to ditch ZurbFoundation since it required jquery and soon found out that mixing frameworks caused problems (used w3.css instead). Got most things working after finding stimulus. I even got Flatpickr working without stimulus - in development, just using the data-behavior approach. 

I was ready to show someone and set up a staging server. Everything worked except for flatpickr. I get a console log msg  that it fired, but any date fields do not show the calendar. The field in not enterable, there are no javascript error. I then used your approach of putting putting it under stimulus, and got the same results.  This is deployed with Capistrano and even though webpacker says staging environment will default to production, I added that to see if it had any affect.

My stimulus control is a stripped down version on one of your examples. Webpacker has been a tedious journey, you can do things different way and there is no real documentation or good examples on getting it all working.  Here is the controller and again, work fine in development.

```javascript
import Flatpickr from "stimulus-flatpickr";
console.log("entering picker")

import { Application } from 'stimulus'

import { definitionsFromContext } from 'stimulus/webpack-helpers'
const application = Application.start()
const context = require.context('../controllers', true, /\.js$/)
application.load(definitionsFromContext(context))

// Manually register Flatpickr as a stimulus controller
application.register('flatpickr', Flatpickr)

// import a theme (could be in your main CSS entry too...)
import "flatpickr/dist/flatpickr.css";

export default class extends Flatpickr {

  initialize() {
     //global options
    console.log("got a picker")
    this.config = {
      altInput: true,
      altFormat: "F j, Y",
      dateFormat: "Y-m-d"
    }
    super.connect();
  }
}
```

I guess it could be my old enemy TurboLinks - I usually had to disable it with Foundation. With no errors, I really don't know where to look.

**Comment by adrienpoly** [comment]
Turbolinks shouldn’t be an issue with Stimulus 

Do you see your console log ‘entering picker’

I am not very familiar with Capistrano, I deploy mostly with Heroku. If you take this app and try to deploy it with Cap does it work?

One thing that I remember from a rare deploy with Cap does your server has node installed? Webpacker require node to build the assets. Or do you build them locally before deploying?

**Comment by salex** [comment]
Yes I see the 'entering picker', never the 'got a picker' in production. The server does have node, but I ruled out Capistrono.

I ran the app on my laptop in production with

```
RAILS_ENV=production bin/rails assets:precompile
RAILS_SERVE_STATIC_FILES=true bin/rails s -e production
``` 

Same problem.  I created a [new issue](https://github.com/rails/webpacker/issues/2413)  on webpacker and referenced flatpickr. It's one of the two and pretty sure it's webpacker, but have no idea what it could be.

Thanks for responding

**Comment by cimm** [comment]
I have the same error with Rails 6.0.2.2. The issue seems to be the CSS, not the JavaScript. Flatpickr works but the CSS styles are not loaded. You can see it if you click in and out of a field, the date is filled in but you don't see the calendar pop-up.

The example mentions `// import a theme (could be in your main CSS entry too...)`, I tried, but it doesn't work. It's not picking up the `@import 'flatpickr/dist/themes/airbnb.css';` in my application.css.scss file.

The pack tag `<%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>` @salex [mentions](https://github.com/rails/webpacker/issues/2413#issuecomment-568523608) is the default tag in Rails 6.0.2.2 so nothing I can change here.

Any ideas?

**Comment by salex** [comment]
Just a little update.

I could not get stimulus-flatpicker to work consitantly in deploying to a staging server so I added a comment to a web packer issue https://github.com/rails/webpacker/issues/2552#issuecomment-625259421 

I don't see anything in your documentation mentions anything about how flatpickr css get added to the assets.complile action or that you have to add a stylesheet_pack_tag.  I fixed it, but don't know why it would work in one application and not another.

Whoops, I forgot that stimulus_flatpicker is used in other applications, not just rails so you would not necessarily add rails specific documentation
